### ISSUE TITLE
Crowd Funding DApp

### ISSUE THREAD

**Issue by apoorva1823000** [Vikash-8090-Yadav/Future.WebNet#147]
### Project title
Crowd Funding DApp

### Project Description
I would like to add a smart contract for Crowd Funding DApp. kindly assign me the task to do so.

### Doc Domain

- [] Solidity , Html, Css , JavaScript , Web3.js / Ether.js
- [] Solidity , ReactJs /NextJs , Web3.js /Ether.js
- [x] Solidity , Python3 , Web3.py
- [] Other , feel free to mention below

#### Are you contributing under any open-source program ?
yes
<hr/>

**Comment by Vikash-8090-Yadav** [comment]
Sorry but in this Repo u have to  Create a full stack Dapp . 
Meanwhile , 
U can also change the Ui  of the exsisiting project  or  Add frontend project in this , 
Hope  u understad . 

PS : Can u please introduce yourself on on the discussion of this community . As it's a Good Habbit in open source .

https://github.com/Vikash-8090-Yadav/Web3.0-World/discussions/146

**Comment by SanjayKumar-M** [comment]
Sure, here are the tasks you will need to complete in order to add a smart contract for a Crowd Funding DApp:

Understand the requirements: Before you begin writing the smart contract, it is important to understand the requirements of the Crowd Funding DApp. This will include understanding the features and functionality that the DApp needs to have, as well as any constraints or limitations that need to be taken into account.

Research existing solutions: Research existing solutions for Crowd Funding DApp on the blockchain to see how they have implemented their smart contracts. This will give you a good understanding of the best practices and pitfalls to avoid when writing your own smart contract.

Design the smart contract: Design the smart contract by creating a high-level architecture of the smart contract and outlining the functions that the smart contract will need to perform. This includes defining the data structures and variables that will be used, as well as the functions that will be used to interact with the smart contract.

Write the smart contract: Write the smart contract code using a smart contract programming language such as Solidity. This will include writing the functions and logic that will be used to perform the operations required by the Crowd Funding DApp.

Test the smart contract: Test the smart contract by creating test cases and running them against the smart contract. This will include testing for errors and bugs, as well as testing the smart contract's functionality.

Deploy the smart contract: Deploy the smart contract to the blockchain network of your choice. This will include creating the necessary transactions and paying the gas fee.

Integrate with the Frontend: Integrate the smart contract with the frontend of the DApp, using web3.js to interact with the smart contract and display the relevant information to the user.

**Comment by Vikash-8090-Yadav** [comment]
@apoorva1823000 @SanjayKumar-M   who   is working on this issue ?

**Comment by SanjayKumar-M** [comment]
> @apoorva1823000 @SanjayKumar-M who is working on this issue ?

Yeah. say what next

**Comment by Vikash-8090-Yadav** [comment]
@SanjayKumar-M  in this repo  you have to ceate full stack crowd funding Dapp . that is by creating frrontend and connecting  with the web3 . if u want  to write only smart contract then, look solidity pathshala repo . Let me know if u want to  work on this or not

**Comment by SanjayKumar-M** [comment]
> @SanjayKumar-M in this repo you have to ceate full stack crowd funding Dapp . that is by creating frrontend and connecting with the web3 . if u want to write only smart contract then, look solidity pathshala repo . Let me know if u want to work on this or not
Yeah sure. I would like to contribute to blockchain part that is smart contracts. If yes, then we can start

**Comment by Vraj1103** [comment]
@Vikash-8090-Yadav  i would like to work on this issue
